frame_id: base_link
robot_base_height: 0.74
table:
  x: 0.43
  y: 0.0
  z: 0.72
  size: [0.64, 0.84, 0.04]
objects:
  red_cube: {x: 0.45, y: -0.20, z: 0.76}
  yellow_cube: {x: 0.45, y: 0.10, z: 0.76}
  blue_cube: {x: 0.45, y: 0.20, z: 0.76}
zones:
  zone_a: {x: 0.30, y: -0.27, z: 0.7425}
  zone_b: {x: 0.30, y: 0.00, z: 0.7425}
  zone_c: {x: 0.30, y: 0.27, z: 0.7425}
cube_size: 0.04
zone_size: [0.14, 0.14, 0.005]
zone_wall_thickness: 0.01
zone_wall_height: 0.035
approach_height: 0.12
grasp_offset: 0.08
